spring.application.name=clone

# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5433/reddit_clone
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== MONGODB =====
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27018/reddit_clone}

# ===== JWT =====
jwt.secret=${JWT_SECRET:dev-only-secret-key-change-in-production-must-be-32chars!!}

# ===== KAFKA =====
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.client-id=${KAFKA_CLIENT_ID:user-service}
spring.kafka.admin.auto-create=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:user-service}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.reddit.clone.*
