// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_Search_FullMethodName         = "/search.SearchService/Search"
	SearchService_IndexPost_FullMethodName      = "/search.SearchService/IndexPost"
	SearchService_IndexCommunity_FullMethodName = "/search.SearchService/IndexCommunity"
	SearchService_IndexUser_FullMethodName      = "/search.SearchService/IndexUser"
	SearchService_IndexComment_FullMethodName   = "/search.SearchService/IndexComment"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	IndexPost(ctx context.Context, in *IndexPostRequest, opts ...grpc.CallOption) (*IndexPostResponse, error)
	IndexCommunity(ctx context.Context, in *IndexCommunityRequest, opts ...grpc.CallOption) (*IndexCommunityResponse, error)
	IndexUser(ctx context.Context, in *IndexUserRequest, opts ...grpc.CallOption) (*IndexUserResponse, error)
	IndexComment(ctx context.Context, in *IndexCommentRequest, opts ...grpc.CallOption) (*IndexCommentResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexPost(ctx context.Context, in *IndexPostRequest, opts ...grpc.CallOption) (*IndexPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexPostResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexCommunity(ctx context.Context, in *IndexCommunityRequest, opts ...grpc.CallOption) (*IndexCommunityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexCommunityResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexUser(ctx context.Context, in *IndexUserRequest, opts ...grpc.CallOption) (*IndexUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexUserResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexComment(ctx context.Context, in *IndexCommentRequest, opts ...grpc.CallOption) (*IndexCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexCommentResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	IndexPost(context.Context, *IndexPostRequest) (*IndexPostResponse, error)
	IndexCommunity(context.Context, *IndexCommunityRequest) (*IndexCommunityResponse, error)
	IndexUser(context.Context, *IndexUserRequest) (*IndexUserResponse, error)
	IndexComment(context.Context, *IndexCommentRequest) (*IndexCommentResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchServiceServer) IndexPost(context.Context, *IndexPostRequest) (*IndexPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexPost not implemented")
}
func (UnimplementedSearchServiceServer) IndexCommunity(context.Context, *IndexCommunityRequest) (*IndexCommunityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexCommunity not implemented")
}
func (UnimplementedSearchServiceServer) IndexUser(context.Context, *IndexUserRequest) (*IndexUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexUser not implemented")
}
func (UnimplementedSearchServiceServer) IndexComment(context.Context, *IndexCommentRequest) (*IndexCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexComment not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexPost(ctx, req.(*IndexPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexCommunity(ctx, req.(*IndexCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexUser(ctx, req.(*IndexUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexComment(ctx, req.(*IndexCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "IndexPost",
			Handler:    _SearchService_IndexPost_Handler,
		},
		{
			MethodName: "IndexCommunity",
			Handler:    _SearchService_IndexCommunity_Handler,
		},
		{
			MethodName: "IndexUser",
			Handler:    _SearchService_IndexUser_Handler,
		},
		{
			MethodName: "IndexComment",
			Handler:    _SearchService_IndexComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
